server:
  port: 8081

spring:
  application:
    name: match-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/match_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/migration/changelog.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: match-service
      auto-offset-reset: earliest
      enable-auto-commit: false

#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.trusted.packages: com.date.datingapp

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springdoc: DEBUG
    com.date.datingapp: DEBUG




